# Generated by Django 2.2.6 on 2019-11-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='4400 University Dr, Fairfax, VA 22030', max_length=200),
        ),
    ]
