# Generated by Django 2.2.6 on 2019-11-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whsapp', '0002_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
