# Generated by Django 2.2.6 on 2019-11-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whsapp', '0003_auto_20191114_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_logo',
            field=models.ImageField(upload_to='static/logos'),
        ),
    ]
